# Generated by Django 5.2.1 on 2025-05-31 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrequestinputfile',
            name='card_qty',
        ),
        migrations.RemoveField(
            model_name='testrequestinputfile',
            name='pin_qty',
        ),
        migrations.RemoveField(
            model_name='testrequestplasticcode',
            name='thermal_colour',
        ),
        migrations.AddField(
            model_name='testrequestpan',
            name='manual_plastic_code_for_pan',
            field=models.CharField(blank=True, help_text='Manually entered plastic code specific to this PAN/group of PANs', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testrequestpan',
            name='plastic_code_lookup',
            field=models.ForeignKey(blank=True, help_text='Link to a predefined plastic code for this PAN/group of PANs', null=True, on_delete=django.db.models.deletion.PROTECT, to='test_requests.plasticcodelookup'),
        ),
        migrations.AlterField(
            model_name='plasticcodelookup',
            name='code',
            field=models.CharField(help_text="The unique plastic code (e.g., '01200733')", max_length=155),
        ),
        migrations.AlterField(
            model_name='testrequestpan',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Indicates if the PAN is available'),
        ),
        migrations.AlterField(
            model_name='testrequestphasedefinition',
            name='name',
            field=models.CharField(help_text='Name of the phase', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='plasticcodelookup',
            unique_together={('customer', 'project', 'tvf_environment', 'code')},
        ),
    ]
