# Generated by Django 5.2.1 on 2025-06-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_requests', '0002_remove_testrequestinputfile_card_qty_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plasticcodelookup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='testrequestpan',
            name='manual_plastic_code_for_pan',
        ),
        migrations.RemoveField(
            model_name='testrequestpan',
            name='plastic_code_lookup',
        ),
        migrations.AddField(
            model_name='testrequestinputfile',
            name='card_qty',
            field=models.IntegerField(default=0, help_text='Quantity of cards in this input file'),
        ),
        migrations.AddField(
            model_name='testrequestinputfile',
            name='pin_qty',
            field=models.IntegerField(default=0, help_text='Quantity of PINs expected in this input file'),
        ),
        migrations.AddField(
            model_name='testrequestplasticcode',
            name='thermal_colour',
            field=models.CharField(blank=True, help_text='Thermal color associated with this plastic code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plasticcodelookup',
            name='code',
            field=models.CharField(help_text="The unique plastic code (e.g., '01200733')", max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='testrequestpan',
            name='is_available',
            field=models.BooleanField(default=False, help_text="Indicates if the PAN is available (from 'Avble' in zc_tvfpans)"),
        ),
        migrations.AlterField(
            model_name='testrequestphasedefinition',
            name='name',
            field=models.CharField(help_text='Name of the phase (e.g., Data Entry, Personalization, Quality, Shipping)', max_length=255, unique=True),
        ),
    ]
