# Generated by Django 5.2.1 on 2025-06-02 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_requests', '0003_alter_plasticcodelookup_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrequestplasticcode',
            name='thermal_colour',
        ),
    ]
