# Generated by Django 5.2.1 on 2025-06-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_requests', '0004_remove_testrequestplasticcode_thermal_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequestplasticcode',
            name='thermal_colour',
            field=models.CharField(blank=True, help_text='Thermal color associated with this plastic code', max_length=255, null=True),
        ),
    ]
