# Generated by Django 5.2.2 on 2025-06-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_requests', '0005_testrequestplasticcode_thermal_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequestshipping',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number for the shipment', max_length=255, null=True),
        ),
    ]
