# Generated by Django 5.2.2 on 2025-06-15 02:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_requests', '0006_testrequestshipping_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='testrequest',
            options={'ordering': ['-request_received_date'], 'verbose_name': 'Test Request (TVF)', 'verbose_name_plural': 'Test Requests (TVFs)'},
        ),
        migrations.AlterModelOptions(
            name='testrequestinputfile',
            options={'ordering': ['-test_request__request_received_date', 'file_name'], 'verbose_name': 'Input File', 'verbose_name_plural': 'Input Files'},
        ),
        migrations.AlterModelOptions(
            name='testrequestpan',
            options={'ordering': ['pan_truncated'], 'verbose_name': 'PAN Entry', 'verbose_name_plural': 'PAN Entries'},
        ),
        migrations.AlterModelOptions(
            name='testrequestphasedefinition',
            options={'ordering': ['order'], 'verbose_name': 'Test Request Phase Definition', 'verbose_name_plural': 'Test Request Phase Definitions'},
        ),
        migrations.AlterModelOptions(
            name='testrequestphaselog',
            options={'ordering': ['timestamp'], 'verbose_name': 'TVF Phase Log', 'verbose_name_plural': 'TVF Phase Logs'},
        ),
        migrations.AlterModelOptions(
            name='testrequestplasticcode',
            options={'ordering': ['-test_request__request_received_date'], 'verbose_name': 'Plastic Code Entry', 'verbose_name_plural': 'Plastic Code Entries'},
        ),
        migrations.AlterModelOptions(
            name='testrequestquality',
            options={'verbose_name': 'Quality Detail', 'verbose_name_plural': 'Quality Details'},
        ),
        migrations.AlterModelOptions(
            name='testrequestshipping',
            options={'verbose_name': 'Shipping Detail', 'verbose_name_plural': 'Shipping Details'},
        ),
        migrations.AlterUniqueTogether(
            name='dispatchmethod',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='testrequestinputfile',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trustportfolder',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'customer', 'tvf_environment')},
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='last_status_update',
        ),
        migrations.RemoveField(
            model_name='testrequestphaselog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='testrequestphaselog',
            name='phase_name',
        ),
        migrations.RemoveField(
            model_name='testrequestphaselog',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='testrequestphaselog',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='testrequestphaselog',
            name='test_request',
        ),
        migrations.AddField(
            model_name='dispatchmethod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_tvfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testrequestphaselog',
            name='action',
            field=models.CharField(default='RECORD_MIGRATED', help_text="e.g., 'Created', 'Submitted', 'Updated', 'Rejected', 'Completed', 'Cancelled'", max_length=255),
        ),
        migrations.AddField(
            model_name='testrequestphaselog',
            name='new_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_phase_logs', to='test_requests.testrequestphasedefinition'),
        ),
        migrations.AddField(
            model_name='testrequestphaselog',
            name='new_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_status_logs', to='test_requests.tvfstatus'),
        ),
        migrations.AddField(
            model_name='testrequestphaselog',
            name='old_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_phase_logs', to='test_requests.testrequestphasedefinition'),
        ),
        migrations.AddField(
            model_name='testrequestphaselog',
            name='old_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_status_logs', to='test_requests.tvfstatus'),
        ),
        migrations.AddField(
            model_name='testrequestphaselog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testrequestphaselog',
            name='tvf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phase_logs', to='test_requests.testrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrequestphaselog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sla_days',
            field=models.IntegerField(default=5, help_text='Service Level Agreement days for shipping.'),
        ),
        migrations.AlterField(
            model_name='dispatchmethod',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_requests.customer'),
        ),
        migrations.AlterField(
            model_name='dispatchmethod',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dispatchmethod',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_requests.project'),
        ),
        migrations.AlterField(
            model_name='plasticcodelookup',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plasticcodelookup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_requests.customer'),
        ),
        migrations.AlterField(
            model_name='plasticcodelookup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plasticcodelookup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_requests.project'),
        ),
        migrations.AlterField(
            model_name='plasticcodelookup',
            name='tvf_environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_requests.tvfenvironment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_requests.customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='tvf_environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_requests.tvfenvironment'),
        ),
        migrations.AlterField(
            model_name='rejectreason',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rejectreason',
            name='reason',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='comments',
            field=models.TextField(blank=True, help_text='General comments for the TVF.', null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='cr_number',
            field=models.CharField(blank=True, help_text='Customer Request Number, if applicable.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='current_phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='current_tvfs', to='test_requests.testrequestphasedefinition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_requests.customer'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='d_code',
            field=models.CharField(blank=True, help_text='Data code related to the TVF.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='pin_config_version',
            field=models.CharField(blank=True, help_text='PIN configuration version.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='pres_config_version',
            field=models.CharField(blank=True, help_text='Presentation configuration version.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='proc_config_version',
            field=models.CharField(blank=True, help_text='Processing configuration version.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_requests.project'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_tvfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='rejected_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='rejected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='rejected_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_requests.rejectreason'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='request_received_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='request_ship_date',
            field=models.DateTimeField(blank=True, help_text='Calculated based on SLA, can be overridden.', null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='run_today',
            field=models.BooleanField(default=False, help_text="Indicates if this TVF is for a 'run today' request."),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='s_code',
            field=models.CharField(blank=True, help_text='Special code related to the TVF.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_requests.tvfstatus'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='trustport_folder_actual',
            field=models.ForeignKey(blank=True, help_text='The actual Trustport folder used for this TVF.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_requests.trustportfolder'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='tvf_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='tvf_environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_requests.tvfenvironment'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='tvf_initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_tvfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='tvf_name',
            field=models.CharField(help_text='Descriptive name for the TVF.', max_length=255),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='tvf_number',
            field=models.CharField(blank=True, help_text='Auto-generated if left blank.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='tvf_pin_mailer',
            field=models.BooleanField(default=False, help_text='Indicates if this TVF includes a PIN mailer.'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='tvf_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_requests.tvftype'),
        ),
        migrations.AlterField(
            model_name='testrequestinputfile',
            name='card_co',
            field=models.CharField(blank=True, help_text='Card company code.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestinputfile',
            name='card_qty',
            field=models.IntegerField(blank=True, help_text='Quantity of cards.', null=True),
        ),
        migrations.AlterField(
            model_name='testrequestinputfile',
            name='card_wo',
            field=models.CharField(blank=True, help_text='Card work order.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestinputfile',
            name='date_file_received',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testrequestinputfile',
            name='file_name',
            field=models.CharField(help_text='Name of the input file.', max_length=255),
        ),
        migrations.AlterField(
            model_name='testrequestinputfile',
            name='pin_co',
            field=models.CharField(blank=True, help_text='PIN company code.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestinputfile',
            name='pin_qty',
            field=models.IntegerField(blank=True, help_text='Quantity of PINs.', null=True),
        ),
        migrations.AlterField(
            model_name='testrequestinputfile',
            name='pin_wo',
            field=models.CharField(blank=True, help_text='PIN work order.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestinputfile',
            name='test_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files_entries', to='test_requests.testrequest'),
        ),
        migrations.AlterField(
            model_name='testrequestpan',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Indicates if the PAN is available for testing.'),
        ),
        migrations.AlterField(
            model_name='testrequestpan',
            name='pan_truncated',
            field=models.CharField(help_text='Truncated PAN (e.g., last 4 digits).', max_length=50),
        ),
        migrations.AlterField(
            model_name='testrequestpan',
            name='test_request_input_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pans', to='test_requests.testrequestinputfile'),
        ),
        migrations.AlterField(
            model_name='testrequestphasedefinition',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='testrequestphasedefinition',
            name='order',
            field=models.IntegerField(help_text='Order in the workflow (lower is earlier).', unique=True),
        ),
        migrations.AlterField(
            model_name='testrequestphaselog',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestplasticcode',
            name='manual_plastic_code',
            field=models.CharField(blank=True, help_text='Enter a plastic code manually if not in the lookup.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestplasticcode',
            name='plastic_code_lookup',
            field=models.ForeignKey(blank=True, help_text='Select a plastic code from the predefined list.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_requests.plasticcodelookup'),
        ),
        migrations.AlterField(
            model_name='testrequestplasticcode',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testrequestplasticcode',
            name='test_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plastic_codes_entries', to='test_requests.testrequest'),
        ),
        migrations.AlterField(
            model_name='testrequestplasticcode',
            name='thermal_colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestquality',
            name='checked_against_specifications',
            field=models.BooleanField(default=False, help_text='Output checked against specifications.'),
        ),
        migrations.AlterField(
            model_name='testrequestquality',
            name='output_accordance_request',
            field=models.BooleanField(default=False, help_text='Output is in accordance with the request.'),
        ),
        migrations.AlterField(
            model_name='testrequestquality',
            name='quality_sign_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_sign_offs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testrequestquality',
            name='quality_sign_off_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestquality',
            name='test_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_details', to='test_requests.testrequest'),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='date_shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='dispatch_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_requests.dispatchmethod'),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='ship_to_address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='ship_to_address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='ship_to_address_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='ship_to_business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='ship_to_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='ship_to_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='ship_to_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='ship_to_postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='ship_to_state_province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='shipping_sign_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_sign_offs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='test_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to='test_requests.testrequest'),
        ),
        migrations.AlterField(
            model_name='testrequestshipping',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number for the shipment.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trustportfolder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_requests.customer'),
        ),
        migrations.AlterField(
            model_name='trustportfolder',
            name='folder_path',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='trustportfolder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_requests.project'),
        ),
        migrations.AlterField(
            model_name='tvfenvironment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tvfstatus',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tvftype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='plasticcodelookup',
            unique_together={('code', 'customer', 'project', 'tvf_environment')},
        ),
        migrations.AlterUniqueTogether(
            name='testrequestplasticcode',
            unique_together={('test_request', 'plastic_code_lookup', 'manual_plastic_code')},
        ),
        migrations.AlterUniqueTogether(
            name='trustportfolder',
            unique_together={('folder_path', 'customer', 'project')},
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dispatch_method_default',
        ),
        migrations.RemoveField(
            model_name='project',
            name='trustport_folder_base',
        ),
    ]
