# Generated by Django 5.2.2 on 2025-06-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_requests', '0007_alter_customer_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustportfolder',
            name='folder_path',
            field=models.CharField(max_length=500),
        ),
    ]
